### ISSUE TITLE
Prediction Throws a ValueError

### ISSUE THREAD

**Issue by shrouti** [janithmehta/StockMarketPrediction#1]
I downloaded your source code and ran it. but on running the same, is throwing the following error. Can you please help resolve?

I have reviewed the ReadMe and installed all required dependencies

![image](https://user-images.githubusercontent.com/34126151/43819972-72a7f6bc-9b02-11e8-8adb-ac43aa78a491.png)

**Comment by janithmehta** [comment]
@shrouti Fixed this issue

**Comment by saachin** [comment]
Hello

Do u have any results of your code
